"""Cytosolic protein entity and generator.

Defines :class:`Pn` (data holder for a single protein entity)
and :class:`PnGen` (generator that places multiple copies via a
SAWLC network inside the volume of interest).

:author: Antonio Martinez-Sanchez
:maintainer: Juan Diego Gallego Nicolás
"""

import random
from pathlib import Path

import mrcfile
import numpy as np

from ...logging_conf import _LOGGER as logger
from ...utils.affine import (
    poly_scale,
    poly_translate,
)
from ...utils.poly import (
    poly_decimate,
    poly_diam,
)
from ...utils.utils import (
    iso_surface,
    lin_map,
    vol_cube,
)


class Pn:
    """Data container for a single placed cytosolic protein entity.

    Stores all parameters associated with one cytosolic protein
    instance as generated by :class:`PnGen`.

    Note:
        Instantiation via :meth:`__init__` is not yet fully
        implemented; use :meth:`PnGen.generate` to create
        instances.
    """

    def __init__(
        self,
        entity_id: int,
        mmer_id: str,
        mmer_svol: np.ndarray,
        mmer_iso: float,
        pmer_l: float,
        pmer_l_max: float,
        pmer_occ: float,
    ):
        """Store protein parameters and trigger structure build.

        Args:
            entity_id (int): Unique entity identifier.
            mmer_id (str): Monomer identifier string.
            mmer_svol (numpy.ndarray): Density sub-volume for the
                monomer.
            mmer_iso (float): Iso-threshold for surface extraction.
            pmer_l (float): Nominal polymer length in Angstroms.
            pmer_l_max (float): Maximum polymer length in Angstroms.
            pmer_occ (float): Target occupancy percentage.

        Raises:
            NotImplementedError: Always; structure building is not
                yet implemented.
        """
        self.__entity_id = entity_id
        self.__mmer_id = mmer_id
        self.__mmer_svol = mmer_svol
        self.__mmer_iso = mmer_iso
        self.__pmer_l = pmer_l
        self.__pmer_l_max = pmer_l_max
        self.__pmer_occ = pmer_occ
        self.__build()

    def __build(self):
        """Build the cytosolic protein entity structure.

        Raises:
            NotImplementedError: Cytosolic protein structure building not yet implemented.
        """
        raise NotImplementedError(
            "Cytosolic protein structure building not yet implemented."
        )


class PnGen:
    """Generator for cytosolic protein entities.

    Loads and pre-processes a density map template, builds an
    isosurface model, and places instances inside a 3-D VOI via
    a SAWLC network.

    Attributes:
        __mmer_id (str): Monomer identifier string.
        __model (numpy.ndarray): Normalised and cubed density map.
        __mmer_iso (float): Iso-threshold for surface extraction.
        __pmer_l (float): Nominal polymer length in Angstroms.
        __pmer_l_max (float): Maximum polymer length in Angstroms.
        __pmer_occ_rg (tuple[float, float]): Occupancy range (lo,
            hi) in percent.
        __pmer_over_tol (float): Allowed surface overlap fraction.
        __surf_dec (float): Decimation ratio for the surface mesh.
        __scale (float): Current scale factor applied to the mesh.
        __model_surf (vtk.vtkPolyData): Decimated isosurface mesh.
        __model_center (numpy.ndarray): Voxel centre of the density
            map.
        __model_mask (numpy.ndarray): Boolean mask of sub-threshold
            voxels.
    """

    def __init__(
        self,
        surf_dec: float,
        mmer_id: str,
        model: np.ndarray,
        mmer_iso: float,
        pmer_l: float,
        pmer_l_max: float,
        pmer_occ_rg: tuple[float, float],
        pmer_over_tol: float = 0.0,
    ):
        """Initialise the cytosolic protein generator.

        Args:
            surf_dec (float): Polygon decimation ratio for the
                isosurface mesh.
            mmer_id (str): Monomer identifier string.
            model (numpy.ndarray): Raw density map to normalise
                and process.
            mmer_iso (float): Iso-threshold for surface extraction.
            pmer_l (float): Nominal polymer length in Angstroms.
            pmer_l_max (float): Maximum polymer length in Angstroms.
            pmer_occ_rg (tuple[float, float]): Occupancy range
                ``(lo, hi)`` in percent.
            pmer_over_tol (float): Allowed surface overlap
                fraction (default 0.0).
        """
        self.__mmer_id = mmer_id
        self.__model = model
        self.__mmer_iso = mmer_iso
        self.__pmer_l = pmer_l
        self.__pmer_l_max = pmer_l_max
        self.__pmer_occ_rg = pmer_occ_rg
        self.__pmer_over_tol = pmer_over_tol
        self.__surf_dec = surf_dec
        self.__scale = 1.0
        self.__gen_model()

    @property
    def pmer_l(self) -> float:
        """Get the polymer length parameter.

        Returns:
            float: Polymer length parameter.
        """
        return self.__pmer_l

    @property
    def pmer_l_max(self) -> float:
        """Get the maximum polymer length parameter.

        Returns:
            float: Maximum polymer length parameter.
        """
        return self.__pmer_l_max

    def __gen_model(self):
        """Generate the cytosolic protein model."""
        self.__model = lin_map(self.__model, lb=0, ub=1)
        self.__model = vol_cube(self.__model)
        self.__model_mask = self.__model < self.__mmer_iso
        self.__model[self.__model_mask] = 0.0
        self.__model_surf = iso_surface(
            self.__model, self.__mmer_iso, closed=False, normals=None
        )
        self.__model_surf = poly_decimate(self.__model_surf, self.__surf_dec)
        self.__model_center = 0.5 * (
            np.asarray(self.__model.shape, dtype=float) - 1
        )
        self.__model_surf = poly_translate(
            self.__model_surf, -self.__model_center
        )

    def set_scale(self, scale: float):
        """Rescale the monomer surface mesh to a new voxel size.

        Args:
            scale (float): New scale factor (voxel size).
        """
        self.__model_surf = poly_scale(self.__model_surf, scale / self.__scale)
        self.__scale = scale

    @property
    def surf_diam(self) -> float:
        """Get the surface diameter of the cytosolic protein model.

        Returns:
            float: Surface diameter of the cytosolic protein model.
        """
        return poly_diam(self.__model_surf)

    def rnd_occ(self) -> float:
        """Generate a random occupancy value within the specified range.

        Returns:
            float: A random occupancy value.
        """
        return random.uniform(self.__pmer_occ_rg[0], self.__pmer_occ_rg[1])

    @property
    def over_tolerance(self) -> float:
        """Get the overlap tolerance parameter.

        Returns:
            float: Overlap tolerance parameter.
        """
        return self.__pmer_over_tol

    @property
    def surf(self):
        """Get the surface representation of the cytosolic protein model.

        Returns:
            vtk.vtkPolyData: Surface representation of the cytosolic protein model.
        """
        return self.__model_surf

    @property
    def model(self) -> np.ndarray:
        """Get the volumetric model of the cytosolic protein.

        Returns:
            np.ndarray: Volumetric model of the cytosolic protein.
        """
        return self.__model

    @property
    def mask(self) -> np.ndarray:
        """Get the mask of the cytosolic protein model.

        Returns:
            np.ndarray: Mask of the cytosolic protein model.
        """
        return self.__model_mask

    @property
    def svol(self) -> np.ndarray:
        """Binary mask used as sub-volume for VOI carving during monomer placement."""
        return self.__model_mask

    @classmethod
    def from_params(
        cls, params: dict, data_path: Path, surf_dec: float
    ) -> "PnGen":
        """Construct a PnGen from a parsed parameter dictionary.

        Args:
            params (dict): Parameter dict with keys MMER_SVOL,
                MMER_ID, MMER_ISO, PMER_L, PMER_L_MAX, PMER_OCC,
                and optionally PMER_OVER_TOL.
            data_path (Path): Root directory for resolving relative
                MMER_SVOL paths.
            surf_dec (float): Polygon decimation ratio passed to
                :func:`~polnet.utils.poly.poly_decimate`.

        Returns:
            PnGen: Fully initialised generator instance.

        Raises:
            FileNotFoundError: If the MMER_SVOL density map cannot
                be loaded.
        """

        # Convert relative path to absolute path
        mmer_path = params["MMER_SVOL"]
        if Path(mmer_path).is_absolute():
            mmer_path = "." + mmer_path
        mmer_path = data_path / mmer_path

        # Check if PMER_OCC is a float or a tuple
        if isinstance(params["PMER_OCC"], (int, float)):
            params["PMER_OCC"] = (params["PMER_OCC"], params["PMER_OCC"])

        try:
            mrc = mrcfile.open(mmer_path, permissive=True, mode="r")
            mmer_svol = np.swapaxes(mrc.data, 0, 2)
            mrc.close()
            return cls(
                surf_dec=surf_dec,
                mmer_id=params["MMER_ID"],
                model=mmer_svol,
                mmer_iso=params["MMER_ISO"],
                pmer_l=params["PMER_L"],
                pmer_l_max=params["PMER_L_MAX"],
                pmer_occ_rg=params["PMER_OCC"],
                pmer_over_tol=params.get("PMER_OVER_TOL", 0.0),
            )
        except Exception as e:
            logger.error(
                "Failed to load monomer subvolume %s: %s", mmer_path, e
            )
            raise FileNotFoundError(
                f"Error loading mmer_svol file {mmer_path}: {e}"
            ) from e

    def generate(self, voi_shape: tuple[int, int, int], v_size: float) -> Pn:
        """Generate a cytosolic protein entity.

        Args:
            voi_shape (tuple[int, int, int]): Shape of the volume of interest (VOI) in voxels.
            v_size (float): Voxel size in Angstroms.

        Returns:
            Pn: Generated cytosolic protein entity.
        """
        raise NotImplementedError(
            "Cytosolic protein generation not yet implemented."
        )


class PnError(Exception):
    """Custom exception for cytosolic protein generation errors."""

    def __init__(self, message: str):
        """Initialise with a descriptive error message.

        Args:
            message (str): Human-readable error description.
        """
        super().__init__(message)
