"""
This script prepares a dataset generated by PolNet to serve as input data to predict with a nn-UNet model
    Input:
        - A directory with the tomograms to process
        - The resolution of the trained model. VERY IMPORTANT: the input MRC tomograms must have set in their headers
        the actual voxel size.
    Output:
        - A new directory with the structure required by nn-UNet for prediction
"""
__author__ = 'Antonio Martinez-Sanchez'

import os
import shutil
import nrrd
import time
import glob
import scipy as sp
import numpy as np

from polnet import lio

ROOT_DIR = '/home/martinez/workspace/data' # '/home/martinez/workspace/data'
in_dir = ROOT_DIR + '/exp_tomos/atpase/tomos' # '/exp_tomos'
out_dir = ROOT_DIR + '/nn-unet/in_predict'
task_id = '007'
task_suffix = 'atpase'
v_size_model = 10 # A/voxel
v_size_decimal = 3 # number of decimal to cut the voxel size precision
norm = True # If true intensity values are normalized wrt mean and variance

# Create the dataset in nn-UNet format
out_task = out_dir + '/Task' + task_id + '_' + task_suffix
if os.path.exists(out_task):
    shutil.rmtree(out_task)
os.makedirs(out_task)
imgs_ts_dir = out_task + '/imagesTs'
os.mkdir(imgs_ts_dir)

# Loop over the input director
tomo_id = 1
for file_path in glob.iglob(in_dir + '/*.*'):
    if not (os.path.splitext(file_path)[1] in ['.mrc', '.rec']):
        continue
    print('Processing tomogram:', file_path)
    v_sizes = lio.read_mrc_v_size(file_path)
    v_sizes = (round(float(v_sizes[0]), v_size_decimal), round(float(v_sizes[1]), v_size_decimal),
               round(float(v_sizes[2]), v_size_decimal))
    if (v_sizes[0] != v_sizes[1]) or (v_sizes[0] != v_sizes[1]):
        print('\t-WARNING: this tomograms cannot pre processes due to its anisotropic voxel size ', v_sizes)
        continue
    v_size_tomo = v_sizes[0]
    tomo = lio.load_mrc(file_path).astype(np.float32)
    if norm:
        tomo.flags.writeable = True
        t_mean, t_std = tomo.mean(), tomo.std()
        tomo = (tomo - t_mean) / t_std
    if v_size_tomo != v_size_model:
        print('\t-Scaling input to tomogram from', v_size_tomo, 'A to fit the model voxel size of', v_size_model, 'A ...')
        tomo = sp.ndimage.zoom(tomo, v_size_tomo / v_size_model)
    nrrd.write(imgs_ts_dir + '/tomo_' + str(tomo_id).zfill(3) + '_0000.nrrd', tomo)
    tomo_id += 1

print('Successfully terminated. (' + time.strftime("%c") + ')')